### ISSUE TITLE
Java loading getting stuck

### ISSUE THREAD

**Issue by rowleya** [SpiNNakerManchester/JavaSpiNNaker#256]
Full path to where you find the problem:
Jstack trace:

```
Full thread dump OpenJDK 64-Bit Server VM (11.0.1+13-Ubuntu-3ubuntu116.04ppa1 mixed mode, sharing):

Threads class SMR info:
_java_thread_list=0x00007f4a40001c50, length=15, elements={
0x00007f4acc012800, 0x00007f4acc4c9000, 0x00007f4acc4cb000, 0x00007f4acc4d0800,
0x00007f4acc4d3000, 0x00007f4acc4d5000, 0x00007f4acc4d7000, 0x00007f4acc505000,
0x00007f4acc509800, 0x00007f4acc97a800, 0x00007f4acc9c0000, 0x00007f4acc9c0800,
0x00007f4acc9c1800, 0x00007f4a1c01e800, 0x00007f4a40001000
}

"main" #1 prio=5 os_prio=0 cpu=8867.57ms elapsed=83076.00s tid=0x00007f4acc012800 nid=0x665 waiting on condition  [0x00007f4ad5ed0000]
   java.lang.Thread.State: WAITING (parking)
at jdk.internal.misc.Unsafe.park(java.base@11.0.1/Native Method)
- parking to wait for  <0x00000000ab561870> (a java.util.concurrent.FutureTask)
at java.util.concurrent.locks.LockSupport.park(java.base@11.0.1/LockSupport.java:194)
at java.util.concurrent.FutureTask.awaitDone(java.base@11.0.1/FutureTask.java:447)
at java.util.concurrent.FutureTask.get(java.base@11.0.1/FutureTask.java:190)
at uk.ac.manchester.spinnaker.front_end.BasicExecutor$Tasks.awaitAndCombineExceptions(BasicExecutor.java:145)
at uk.ac.manchester.spinnaker.front_end.dse.FastExecuteDataSpecification.loadCores(FastExecuteDataSpecification.java:212)
at uk.ac.manchester.spinnaker.front_end.CommandLineInterface.dseAppMonRun(CommandLineInterface.java:304)
at uk.ac.manchester.spinnaker.front_end.CommandLineInterface.main(CommandLineInterface.java:175)

"Reference Handler" #2 daemon prio=10 os_prio=0 cpu=51.71ms elapsed=83075.99s tid=0x00007f4acc4c9000 nid=0x66d waiting on condition  [0x00007f4a608ef000]
   java.lang.Thread.State: RUNNABLE
at java.lang.ref.Reference.waitForReferencePendingList(java.base@11.0.1/Native Method)
at java.lang.ref.Reference.processPendingReferences(java.base@11.0.1/Reference.java:241)
at java.lang.ref.Reference$ReferenceHandler.run(java.base@11.0.1/Reference.java:213)

"Finalizer" #3 daemon prio=8 os_prio=0 cpu=45.96ms elapsed=83075.99s tid=0x00007f4acc4cb000 nid=0x66f in Object.wait()  [0x00007f4a607ee000]
   java.lang.Thread.State: WAITING (on object monitor)
at java.lang.Object.wait(java.base@11.0.1/Native Method)
- waiting on <no object reference available>
at java.lang.ref.ReferenceQueue.remove(java.base@11.0.1/ReferenceQueue.java:155)
- waiting to re-lock in wait() <0x0000000082ba71e8> (a java.lang.ref.ReferenceQueue$Lock)
at java.lang.ref.ReferenceQueue.remove(java.base@11.0.1/ReferenceQueue.java:176)
at java.lang.ref.Finalizer$FinalizerThread.run(java.base@11.0.1/Finalizer.java:170)

"Signal Dispatcher" #4 daemon prio=9 os_prio=0 cpu=0.32ms elapsed=83075.98s tid=0x00007f4acc4d0800 nid=0x671 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #5 daemon prio=9 os_prio=0 cpu=8606.69ms elapsed=83075.98s tid=0x00007f4acc4d3000 nid=0x672 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

"C1 CompilerThread0" #15 daemon prio=9 os_prio=0 cpu=927.56ms elapsed=83075.98s tid=0x00007f4acc4d5000 nid=0x673 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

"Sweeper thread" #20 daemon prio=9 os_prio=0 cpu=590.12ms elapsed=83075.98s tid=0x00007f4acc4d7000 nid=0x674 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Service Thread" #21 daemon prio=9 os_prio=0 cpu=0.11ms elapsed=83075.96s tid=0x00007f4acc505000 nid=0x676 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Common-Cleaner" #22 daemon prio=8 os_prio=0 cpu=52.89ms elapsed=83075.96s tid=0x00007f4acc509800 nid=0x678 in Object.wait()  [0x00007f4a37cfb000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
at java.lang.Object.wait(java.base@11.0.1/Native Method)
- waiting on <no object reference available>
at java.lang.ref.ReferenceQueue.remove(java.base@11.0.1/ReferenceQueue.java:155)
- waiting to re-lock in wait() <0x0000000082b75bb0> (a java.lang.ref.ReferenceQueue$Lock)
at jdk.internal.ref.CleanerImpl.run(java.base@11.0.1/CleanerImpl.java:148)
at java.lang.Thread.run(java.base@11.0.1/Thread.java:834)
at jdk.internal.misc.InnocuousThread.run(java.base@11.0.1/InnocuousThread.java:134)

"pool-2-thread-1" #25 prio=5 os_prio=0 cpu=103145.07ms elapsed=83066.74s tid=0x00007f4acc97a800 nid=0x6e6 runnable  [0x00007f4a375d0000]
   java.lang.Thread.State: RUNNABLE
at sun.nio.ch.EPoll.wait(java.base@11.0.1/Native Method)
at sun.nio.ch.EPollSelectorImpl.doSelect(java.base@11.0.1/EPollSelectorImpl.java:120)
at sun.nio.ch.SelectorImpl.lockAndDoSelect(java.base@11.0.1/SelectorImpl.java:124)
- locked <0x0000000087c3b550> (a sun.nio.ch.Util$2)
- locked <0x0000000087c3b4c8> (a sun.nio.ch.EPollSelectorImpl)
at sun.nio.ch.SelectorImpl.select(java.base@11.0.1/SelectorImpl.java:136)
at uk.ac.manchester.spinnaker.connections.UDPConnection.isReadyToReceive(UDPConnection.java:572)
at uk.ac.manchester.spinnaker.connections.UDPConnection.receive(UDPConnection.java:296)
at uk.ac.manchester.spinnaker.front_end.dse.ThrottledConnection.receive(ThrottledConnection.java:113)
at uk.ac.manchester.spinnaker.front_end.dse.FastExecuteDataSpecification$BoardWorker.fastWrite(FastExecuteDataSpecification.java:696)
at uk.ac.manchester.spinnaker.front_end.dse.FastExecuteDataSpecification$BoardWorker.writeRegion(FastExecuteDataSpecification.java:623)
at uk.ac.manchester.spinnaker.front_end.dse.FastExecuteDataSpecification$BoardWorker.loadCoreFromExecutor(FastExecuteDataSpecification.java:491)
at uk.ac.manchester.spinnaker.front_end.dse.FastExecuteDataSpecification$BoardWorker.loadCore(FastExecuteDataSpecification.java:452)
at uk.ac.manchester.spinnaker.front_end.dse.FastExecuteDataSpecification.loadBoard(FastExecuteDataSpecification.java:244)
at uk.ac.manchester.spinnaker.front_end.dse.FastExecuteDataSpecification.lambda$loadCores$1(FastExecuteDataSpecification.java:211)
at uk.ac.manchester.spinnaker.front_end.dse.FastExecuteDataSpecification$$Lambda$101/0x00000008401c6840.call(Unknown Source)
at uk.ac.manchester.spinnaker.front_end.BasicExecutor.collectExceptions(BasicExecutor.java:77)
at uk.ac.manchester.spinnaker.front_end.BasicExecutor.lambda$submitTasks$0(BasicExecutor.java:57)
at uk.ac.manchester.spinnaker.front_end.BasicExecutor$$Lambda$102/0x00000008401c6c40.call(Unknown Source)
at java.util.concurrent.FutureTask.run(java.base@11.0.1/FutureTask.java:264)
at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.1/ThreadPoolExecutor.java:1128)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.1/ThreadPoolExecutor.java:628)
at java.lang.Thread.run(java.base@11.0.1/Thread.java:834)

"pool-2-thread-2" #26 prio=5 os_prio=0 cpu=101297.45ms elapsed=83066.74s tid=0x00007f4acc9c0000 nid=0x6e7 runnable  [0x00007f4a36ec4000]
   java.lang.Thread.State: RUNNABLE
at sun.nio.ch.EPoll.wait(java.base@11.0.1/Native Method)
at sun.nio.ch.EPollSelectorImpl.doSelect(java.base@11.0.1/EPollSelectorImpl.java:120)
at sun.nio.ch.SelectorImpl.lockAndDoSelect(java.base@11.0.1/SelectorImpl.java:124)
- locked <0x0000000087ceae90> (a sun.nio.ch.Util$2)
- locked <0x0000000087ceae08> (a sun.nio.ch.EPollSelectorImpl)
at sun.nio.ch.SelectorImpl.select(java.base@11.0.1/SelectorImpl.java:136)
at uk.ac.manchester.spinnaker.connections.UDPConnection.isReadyToReceive(UDPConnection.java:572)
at uk.ac.manchester.spinnaker.connections.UDPConnection.receive(UDPConnection.java:296)
at uk.ac.manchester.spinnaker.front_end.dse.ThrottledConnection.receive(ThrottledConnection.java:113)
at uk.ac.manchester.spinnaker.front_end.dse.FastExecuteDataSpecification$BoardWorker.fastWrite(FastExecuteDataSpecification.java:696)
at uk.ac.manchester.spinnaker.front_end.dse.FastExecuteDataSpecification$BoardWorker.writeRegion(FastExecuteDataSpecification.java:623)
at uk.ac.manchester.spinnaker.front_end.dse.FastExecuteDataSpecification$BoardWorker.loadCoreFromExecutor(FastExecuteDataSpecification.java:491)
at uk.ac.manchester.spinnaker.front_end.dse.FastExecuteDataSpecification$BoardWorker.loadCore(FastExecuteDataSpecification.java:452)
at uk.ac.manchester.spinnaker.front_end.dse.FastExecuteDataSpecification.loadBoard(FastExecuteDataSpecification.java:244)
at uk.ac.manchester.spinnaker.front_end.dse.FastExecuteDataSpecification.lambda$loadCores$1(FastExecuteDataSpecification.java:211)
at uk.ac.manchester.spinnaker.front_end.dse.FastExecuteDataSpecification$$Lambda$101/0x00000008401c6840.call(Unknown Source)
at uk.ac.manchester.spinnaker.front_end.BasicExecutor.collectExceptions(BasicExecutor.java:77)
at uk.ac.manchester.spinnaker.front_end.BasicExecutor.lambda$submitTasks$0(BasicExecutor.java:57)
at uk.ac.manchester.spinnaker.front_end.BasicExecutor$$Lambda$102/0x00000008401c6c40.call(Unknown Source)
at java.util.concurrent.FutureTask.run(java.base@11.0.1/FutureTask.java:264)
at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.1/ThreadPoolExecutor.java:1128)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.1/ThreadPoolExecutor.java:628)
at java.lang.Thread.run(java.base@11.0.1/Thread.java:834)

"pool-2-thread-3" #27 prio=5 os_prio=0 cpu=102688.04ms elapsed=83066.74s tid=0x00007f4acc9c0800 nid=0x6e8 runnable  [0x00007f4a377d2000]
   java.lang.Thread.State: RUNNABLE
at sun.nio.ch.EPoll.wait(java.base@11.0.1/Native Method)
at sun.nio.ch.EPollSelectorImpl.doSelect(java.base@11.0.1/EPollSelectorImpl.java:120)
at sun.nio.ch.SelectorImpl.lockAndDoSelect(java.base@11.0.1/SelectorImpl.java:124)
- locked <0x00000000b8811598> (a sun.nio.ch.Util$2)
- locked <0x00000000b88112e8> (a sun.nio.ch.EPollSelectorImpl)
at sun.nio.ch.SelectorImpl.select(java.base@11.0.1/SelectorImpl.java:136)
at uk.ac.manchester.spinnaker.connections.UDPConnection.isReadyToReceive(UDPConnection.java:572)
at uk.ac.manchester.spinnaker.connections.UDPConnection.receive(UDPConnection.java:296)
at uk.ac.manchester.spinnaker.front_end.dse.ThrottledConnection.receive(ThrottledConnection.java:113)
at uk.ac.manchester.spinnaker.front_end.dse.FastExecuteDataSpecification$BoardWorker.fastWrite(FastExecuteDataSpecification.java:696)
at uk.ac.manchester.spinnaker.front_end.dse.FastExecuteDataSpecification$BoardWorker.writeRegion(FastExecuteDataSpecification.java:623)
at uk.ac.manchester.spinnaker.front_end.dse.FastExecuteDataSpecification$BoardWorker.loadCoreFromExecutor(FastExecuteDataSpecification.java:491)
at uk.ac.manchester.spinnaker.front_end.dse.FastExecuteDataSpecification$BoardWorker.loadCore(FastExecuteDataSpecification.java:452)
at uk.ac.manchester.spinnaker.front_end.dse.FastExecuteDataSpecification.loadBoard(FastExecuteDataSpecification.java:244)
at uk.ac.manchester.spinnaker.front_end.dse.FastExecuteDataSpecification.lambda$loadCores$1(FastExecuteDataSpecification.java:211)
at uk.ac.manchester.spinnaker.front_end.dse.FastExecuteDataSpecification$$Lambda$101/0x00000008401c6840.call(Unknown Source)
at uk.ac.manchester.spinnaker.front_end.BasicExecutor.collectExceptions(BasicExecutor.java:77)
at uk.ac.manchester.spinnaker.front_end.BasicExecutor.lambda$submitTasks$0(BasicExecutor.java:57)
at uk.ac.manchester.spinnaker.front_end.BasicExecutor$$Lambda$102/0x00000008401c6c40.call(Unknown Source)
at java.util.concurrent.FutureTask.run(java.base@11.0.1/FutureTask.java:264)
at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.1/ThreadPoolExecutor.java:1128)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.1/ThreadPoolExecutor.java:628)
at java.lang.Thread.run(java.base@11.0.1/Thread.java:834)

"pool-2-thread-4" #28 prio=5 os_prio=0 cpu=103489.42ms elapsed=83066.74s tid=0x00007f4acc9c1800 nid=0x6e9 runnable  [0x00007f4a36bc3000]
   java.lang.Thread.State: RUNNABLE
at sun.nio.ch.EPoll.wait(java.base@11.0.1/Native Method)
at sun.nio.ch.EPollSelectorImpl.doSelect(java.base@11.0.1/EPollSelectorImpl.java:120)
at sun.nio.ch.SelectorImpl.lockAndDoSelect(java.base@11.0.1/SelectorImpl.java:124)
- locked <0x0000000087c46aa8> (a sun.nio.ch.Util$2)
- locked <0x0000000087c46588> (a sun.nio.ch.EPollSelectorImpl)
at sun.nio.ch.SelectorImpl.select(java.base@11.0.1/SelectorImpl.java:136)
at uk.ac.manchester.spinnaker.connections.UDPConnection.isReadyToReceive(UDPConnection.java:572)
at uk.ac.manchester.spinnaker.connections.UDPConnection.receive(UDPConnection.java:296)
at uk.ac.manchester.spinnaker.front_end.dse.ThrottledConnection.receive(ThrottledConnection.java:113)
at uk.ac.manchester.spinnaker.front_end.dse.FastExecuteDataSpecification$BoardWorker.fastWrite(FastExecuteDataSpecification.java:696)
at uk.ac.manchester.spinnaker.front_end.dse.FastExecuteDataSpecification$BoardWorker.writeRegion(FastExecuteDataSpecification.java:623)
at uk.ac.manchester.spinnaker.front_end.dse.FastExecuteDataSpecification$BoardWorker.loadCoreFromExecutor(FastExecuteDataSpecification.java:491)
at uk.ac.manchester.spinnaker.front_end.dse.FastExecuteDataSpecification$BoardWorker.loadCore(FastExecuteDataSpecification.java:452)
at uk.ac.manchester.spinnaker.front_end.dse.FastExecuteDataSpecification.loadBoard(FastExecuteDataSpecification.java:244)
at uk.ac.manchester.spinnaker.front_end.dse.FastExecuteDataSpecification.lambda$loadCores$1(FastExecuteDataSpecification.java:211)
at uk.ac.manchester.spinnaker.front_end.dse.FastExecuteDataSpecification$$Lambda$101/0x00000008401c6840.call(Unknown Source)
at uk.ac.manchester.spinnaker.front_end.BasicExecutor.collectExceptions(BasicExecutor.java:77)
at uk.ac.manchester.spinnaker.front_end.BasicExecutor.lambda$submitTasks$0(BasicExecutor.java:57)
at uk.ac.manchester.spinnaker.front_end.BasicExecutor$$Lambda$102/0x00000008401c6c40.call(Unknown Source)
at java.util.concurrent.FutureTask.run(java.base@11.0.1/FutureTask.java:264)
at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.1/ThreadPoolExecutor.java:1128)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.1/ThreadPoolExecutor.java:628)
at java.lang.Thread.run(java.base@11.0.1/Thread.java:834)

"ThrottledConnection.Closer" #29 daemon prio=5 os_prio=0 cpu=12.49ms elapsed=72816.40s tid=0x00007f4a1c01e800 nid=0x14795 waiting on condition  [0x00007f4a369c1000]
   java.lang.Thread.State: WAITING (parking)
at jdk.internal.misc.Unsafe.park(java.base@11.0.1/Native Method)
- parking to wait for  <0x0000000087c9f158> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
at java.util.concurrent.locks.LockSupport.park(java.base@11.0.1/LockSupport.java:194)
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(java.base@11.0.1/AbstractQueuedSynchronizer.java:2081)
at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(java.base@11.0.1/ScheduledThreadPoolExecutor.java:1170)
at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(java.base@11.0.1/ScheduledThreadPoolExecutor.java:899)
at java.util.concurrent.ThreadPoolExecutor.getTask(java.base@11.0.1/ThreadPoolExecutor.java:1054)
at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.1/ThreadPoolExecutor.java:1114)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.1/ThreadPoolExecutor.java:628)
at java.lang.Thread.run(java.base@11.0.1/Thread.java:834)

"Attach Listener" #30 daemon prio=9 os_prio=0 cpu=0.50ms elapsed=230.88s tid=0x00007f4a40001000 nid=0x17858 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"VM Thread" os_prio=0 cpu=5561.80ms elapsed=83075.99s tid=0x00007f4acc4c6800 nid=0x66b runnable  

"GC Thread#0" os_prio=0 cpu=1163.20ms elapsed=83076.00s tid=0x00007f4acc02a000 nid=0x666 runnable  

"GC Thread#1" os_prio=0 cpu=1299.26ms elapsed=83075.03s tid=0x00007f4a54001000 nid=0x685 runnable  

"GC Thread#2" os_prio=0 cpu=1303.68ms elapsed=83075.03s tid=0x00007f4a54002800 nid=0x686 runnable  

"GC Thread#3" os_prio=0 cpu=1220.02ms elapsed=83075.03s tid=0x00007f4a54004000 nid=0x687 runnable  

"GC Thread#4" os_prio=0 cpu=1360.78ms elapsed=83075.03s tid=0x00007f4a54005800 nid=0x688 runnable  

"GC Thread#5" os_prio=0 cpu=1346.69ms elapsed=83075.03s tid=0x00007f4a54007000 nid=0x689 runnable  

"GC Thread#6" os_prio=0 cpu=1195.24ms elapsed=83075.03s tid=0x00007f4a54008800 nid=0x68a runnable  

"GC Thread#7" os_prio=0 cpu=1138.04ms elapsed=83075.02s tid=0x00007f4a5400a000 nid=0x68b runnable  

"GC Thread#8" os_prio=0 cpu=1185.74ms elapsed=83075.02s tid=0x00007f4a5400b800 nid=0x68c runnable  

"GC Thread#9" os_prio=0 cpu=1209.40ms elapsed=83075.02s tid=0x00007f4a5400d000 nid=0x68d runnable  

"GC Thread#10" os_prio=0 cpu=1181.29ms elapsed=83075.02s tid=0x00007f4a5400e800 nid=0x68e runnable  

"GC Thread#11" os_prio=0 cpu=1272.90ms elapsed=83075.02s tid=0x00007f4a54010000 nid=0x68f runnable  

"GC Thread#12" os_prio=0 cpu=1180.44ms elapsed=83075.02s tid=0x00007f4a54012000 nid=0x690 runnable  

"GC Thread#13" os_prio=0 cpu=1322.38ms elapsed=83075.02s tid=0x00007f4a54013800 nid=0x691 runnable  

"GC Thread#14" os_prio=0 cpu=1323.35ms elapsed=83075.02s tid=0x00007f4a54015000 nid=0x692 runnable  

"GC Thread#15" os_prio=0 cpu=1237.69ms elapsed=83075.02s tid=0x00007f4a54016800 nid=0x693 runnable  

"GC Thread#16" os_prio=0 cpu=1166.93ms elapsed=83075.02s tid=0x00007f4a54018000 nid=0x694 runnable  

"GC Thread#17" os_prio=0 cpu=1181.77ms elapsed=83075.02s tid=0x00007f4a54019800 nid=0x695 runnable  

"GC Thread#18" os_prio=0 cpu=1189.74ms elapsed=83075.02s tid=0x00007f4a5401b000 nid=0x696 runnable  

"GC Thread#19" os_prio=0 cpu=1220.13ms elapsed=83075.02s tid=0x00007f4a5401c800 nid=0x697 runnable  

"GC Thread#20" os_prio=0 cpu=1247.49ms elapsed=83075.02s tid=0x00007f4a5401e000 nid=0x698 runnable  

"GC Thread#21" os_prio=0 cpu=1277.57ms elapsed=83075.02s tid=0x00007f4a5401f800 nid=0x699 runnable  

"GC Thread#22" os_prio=0 cpu=1146.87ms elapsed=83075.02s tid=0x00007f4a54021000 nid=0x69a runnable  

"G1 Main Marker" os_prio=0 cpu=93.52ms elapsed=83076.00s tid=0x00007f4acc099800 nid=0x667 runnable  

"G1 Conc#0" os_prio=0 cpu=13494.21ms elapsed=83076.00s tid=0x00007f4acc09b800 nid=0x668 runnable  

"G1 Conc#1" os_prio=0 cpu=13115.65ms elapsed=82307.37s tid=0x00007f4a64001000 nid=0x1f16 runnable  

"G1 Conc#2" os_prio=0 cpu=13432.21ms elapsed=82307.37s tid=0x00007f4a64002000 nid=0x1f17 runnable  

"G1 Conc#3" os_prio=0 cpu=13520.47ms elapsed=82307.37s tid=0x00007f4a64003000 nid=0x1f18 runnable  

"G1 Conc#4" os_prio=0 cpu=13091.16ms elapsed=82307.37s tid=0x00007f4a64004000 nid=0x1f19 runnable  

"G1 Conc#5" os_prio=0 cpu=13200.62ms elapsed=82307.37s tid=0x00007f4a64004800 nid=0x1f1a runnable  

"G1 Refine#0" os_prio=0 cpu=11.43ms elapsed=83076.00s tid=0x00007f4acc40c800 nid=0x669 runnable  

"G1 Refine#1" os_prio=0 cpu=11.07ms elapsed=83065.64s tid=0x00007f4a58001000 nid=0x6ec runnable  

"G1 Refine#2" os_prio=0 cpu=10.90ms elapsed=83065.64s tid=0x00007f4a0000d000 nid=0x6ed runnable  

"G1 Refine#3" os_prio=0 cpu=10.51ms elapsed=83065.64s tid=0x00007f4a04031000 nid=0x6ee runnable  

"G1 Refine#4" os_prio=0 cpu=10.34ms elapsed=83065.64s tid=0x00007f49f8058800 nid=0x6ef runnable  

"G1 Refine#5" os_prio=0 cpu=10.14ms elapsed=83065.64s tid=0x00007f49fc011800 nid=0x6f0 runnable  

"G1 Refine#6" os_prio=0 cpu=9.70ms elapsed=83065.64s tid=0x00007f49f0001000 nid=0x6f1 runnable  

"G1 Refine#7" os_prio=0 cpu=9.34ms elapsed=83065.64s tid=0x00007f499c001000 nid=0x6f2 runnable  

"G1 Refine#8" os_prio=0 cpu=8.97ms elapsed=83065.64s tid=0x00007f4990001000 nid=0x6f3 runnable  

"G1 Refine#9" os_prio=0 cpu=8.56ms elapsed=83065.64s tid=0x00007f4994001000 nid=0x6f4 runnable  

"G1 Refine#10" os_prio=0 cpu=8.41ms elapsed=83065.64s tid=0x00007f4988001000 nid=0x6f5 runnable  

"G1 Refine#11" os_prio=0 cpu=8.04ms elapsed=83065.64s tid=0x00007f498c001000 nid=0x6f6 runnable  

"G1 Refine#12" os_prio=0 cpu=8.09ms elapsed=83065.64s tid=0x00007f4980001000 nid=0x6f7 runnable  

"G1 Refine#13" os_prio=0 cpu=7.74ms elapsed=83065.64s tid=0x00007f497c001000 nid=0x6f8 runnable  

"G1 Refine#14" os_prio=0 cpu=7.61ms elapsed=83065.64s tid=0x00007f4974001000 nid=0x6f9 runnable  

"G1 Refine#15" os_prio=0 cpu=0.16ms elapsed=83065.64s tid=0x00007f4978001000 nid=0x6fa runnable  

"G1 Refine#16" os_prio=0 cpu=0.07ms elapsed=83065.64s tid=0x00007f496c001000 nid=0x6fb runnable  

"G1 Young RemSet Sampling" os_prio=0 cpu=12213.18ms elapsed=83076.00s tid=0x00007f4acc40e800 nid=0x66a runnable  
"VM Periodic Task Thread" os_prio=0 cpu=31390.03ms elapsed=83075.96s tid=0x00007f4acc507800 nid=0x677 waiting on condition  

JNI global refs: 29, weak refs: 5
```

What is the problem you see?
Has been loading since 2020-02-08 19:41:05.  Not responding, not timing out.

What do you think it should do instead?
Either load or time out.

What version of our software are you using?
Master as of 2020-02-08 (updated and rebuilt).

**Comment by rowleya** [comment]
[jspin.zip](https://github.com/SpiNNakerManchester/JavaSpiNNaker/files/4177543/jspin.zip)

**Comment by rowleya** [comment]
Sorry, just looked this morning and it is still running... it seems to be taking quite a while but it is a 600 board job!
